name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Check PEP8
        run: |
          python -m flake8

      - name: Run tests
        env:
          OC_LETTING_SK: ${{ secrets.OC_LETTING_SK }}
        run: pytest --cov-config=.coveragerc --cov=. --cov-fail-under=80

  build_docker:
    needs: build_app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build \
          --push \
          -t tmenanteau/oc_lettings:${{ github.sha }} \
          --build-arg OC_LETTING_SENTRY_KEY="${{ secrets.OC_LETTING_SENTRY_KEY }}" \
          --build-arg OC_LETTING_SK="${{ secrets.OC_LETTING_SK }}" \
          .
